defmodule SelectoMix.DomainImport do
  @moduledoc """
  Builds non-writing import plans for normalized Selecto domain artifacts.

  This is the first import/readback slice. It verifies an artifact through the
  same check path used by the other artifact tasks, then reports what a future
  importer could reconstruct without writing generated domain files yet.
  """

  alias SelectoMix.DomainExport

  @format "selecto.domain_import_plan"
  @format_version 1

  @known_sections [
    "source",
    "schemas",
    "joins",
    "filters",
    "functions",
    "query_members",
    "published_views",
    "detail_actions",
    "writes",
    "capabilities",
    "actions",
    "source_relationships",
    "choice_sources"
  ]

  @spec plan_file(Path.t(), keyword()) :: {:ok, map()} | {:error, DomainExport.artifact_error()}
  def plan_file(path, opts \\ []) do
    with {:ok, check} <- DomainExport.check_file(path, opts) do
      {:ok, plan(check, opts)}
    end
  end

  @spec plan(map(), keyword()) :: map()
  def plan(%{artifact: artifact} = check, opts \\ []) do
    summary = DomainExport.summary(check)
    domain = Map.get(artifact, "domain", %{})
    runtime_placeholders = runtime_placeholders(domain)
    sections = sections(domain, summary, runtime_placeholders)
    preview = preview(summary, sections, runtime_placeholders, opts)

    %{
      "format" => @format,
      "format_version" => @format_version,
      "mode" => "check",
      "source" => %{
        "path" => Map.get(check, :path),
        "artifact_format" => Map.get(artifact, "format"),
        "artifact_format_version" => Map.get(artifact, "format_version"),
        "domain_module" => Map.get(artifact, "domain_module"),
        "schema_version" => Map.get(artifact, "schema_version"),
        "name" => Map.get(summary, :name)
      },
      "preview" => preview,
      "source_preview" => source_preview(domain, preview, runtime_placeholders),
      "sections" => sections,
      "runtime_placeholders" => runtime_placeholders,
      "diagnostics" => DomainExport.json_safe(Map.fetch!(summary, :diagnostics)),
      "write" => %{
        "status" => "not_implemented",
        "message" => "No files are written by import --check."
      }
    }
  end

  @spec encode!(map(), keyword()) :: String.t()
  def encode!(plan, opts \\ []) do
    DomainExport.encode!(plan, opts)
  end

  defp preview(summary, sections, runtime_placeholders, opts) do
    target_module = target_module(summary, opts)
    output_dir = opts[:output_dir] || "lib"
    target_file = opts[:target_file] || module_file(target_module, output_dir)
    blocked? = map_get(runtime_placeholders, "count", 0) > 0

    %{
      "status" => if(blocked?, do: "partial", else: "ready"),
      "target_module" => target_module,
      "target_file" => target_file,
      "domain_function" => "domain/0",
      "render_strategy" => "literal_domain_map",
      "write_enabled" => false,
      "blocked_by_runtime_placeholders" => blocked?,
      "reconstructable_sections" => sections_by_status(sections, "reconstructable"),
      "partial_sections" => sections_by_status(sections, "partial_runtime_placeholders"),
      "preserved_unmodeled_sections" => sections_by_status(sections, "preserved_unmodeled")
    }
  end

  defp source_preview(domain, preview, runtime_placeholders) do
    content = render_source(Map.fetch!(preview, "target_module"), domain)

    %{
      "status" => Map.fetch!(preview, "status"),
      "language" => "elixir",
      "target_module" => Map.fetch!(preview, "target_module"),
      "target_file" => Map.fetch!(preview, "target_file"),
      "domain_function" => Map.fetch!(preview, "domain_function"),
      "write_enabled" => false,
      "includes_runtime_placeholders" => map_get(runtime_placeholders, "count", 0) > 0,
      "line_count" => source_line_count(content),
      "content" => content
    }
  end

  defp render_source(target_module, domain) do
    domain_literal =
      domain
      |> inspect(pretty: true, limit: :infinity, printable_limit: :infinity, width: 98)
      |> indent(4)

    """
    defmodule #{module_name(target_module)} do
      @moduledoc \"\"\"
      Selecto domain import preview.

      Generated by `mix selecto.domain.import --check`.
      Preview only; no files were written.
      \"\"\"

      def domain do
    #{domain_literal}
      end
    end
    """
  end

  defp module_name(module) do
    module
    |> to_string()
    |> String.replace_prefix("Elixir.", "")
  end

  defp indent(content, spaces) do
    padding = String.duplicate(" ", spaces)

    content
    |> String.split("\n")
    |> Enum.map_join("\n", &(padding <> &1))
  end

  defp source_line_count(content) do
    content
    |> String.split("\n", trim: true)
    |> length()
  end

  defp target_module(summary, opts) do
    opts[:target_module] ||
      Map.get(summary, :domain_module) ||
      "Imported.SelectoDomain"
  end

  defp module_file(module, output_dir) do
    module_path =
      module
      |> to_string()
      |> String.replace_prefix("Elixir.", "")
      |> Macro.underscore()

    Path.join(output_dir, "#{module_path}.ex")
  end

  defp sections_by_status(sections, status) do
    sections
    |> Enum.filter(&(Map.get(&1, "status") == status))
    |> Enum.map(&Map.fetch!(&1, "name"))
    |> Enum.sort()
  end

  defp sections(domain, summary, runtime_placeholders) do
    classes = section_classes(Map.fetch!(summary, :sections))

    @known_sections
    |> Enum.filter(&section_present?(domain, &1))
    |> Kernel.++(Map.keys(classes))
    |> Enum.uniq()
    |> Enum.sort()
    |> Enum.map(fn section ->
      present? = section_present?(domain, section)
      count = section_count(domain, section)
      class = Map.get(classes, section, "unclassified")
      placeholder_count = section_placeholder_count(runtime_placeholders, section)

      %{
        "name" => section,
        "class" => class,
        "present" => present?,
        "count" => count,
        "runtime_placeholders" => placeholder_count,
        "status" => section_status(present?, class, placeholder_count)
      }
    end)
  end

  defp section_classes(sections) do
    Enum.reduce(["canonical", "projection", "proposed", "unknown"], %{}, fn class, acc ->
      sections
      |> map_get(class, [])
      |> list_or_empty()
      |> Enum.reduce(acc, fn section, class_acc ->
        Map.put(class_acc, to_string(section), class)
      end)
    end)
  end

  defp section_status(false, _class, _placeholder_count), do: "absent"
  defp section_status(true, "unknown", _placeholder_count), do: "preserved_unmodeled"
  defp section_status(true, _class, count) when count > 0, do: "partial_runtime_placeholders"
  defp section_status(true, _class, _placeholder_count), do: "reconstructable"

  defp section_present?(domain, "source"), do: is_map(map_get(domain, "source"))

  defp section_present?(domain, section) do
    case map_get(domain, section) do
      nil -> false
      value when is_map(value) -> map_size(value) > 0
      value when is_list(value) -> length(value) > 0
      _value -> true
    end
  end

  defp section_count(domain, "source") do
    if is_map(map_get(domain, "source")), do: 1, else: 0
  end

  defp section_count(domain, "query_members") do
    domain
    |> map_get("query_members", %{})
    |> count_query_members()
  end

  defp section_count(domain, section) do
    domain
    |> map_get(section)
    |> count_value()
  end

  defp count_query_members(query_members) when is_map(query_members) do
    query_members
    |> Map.values()
    |> Enum.reduce(0, fn
      members, count when is_map(members) -> count + map_size(members)
      members, count when is_list(members) -> count + length(members)
      _members, count -> count
    end)
  end

  defp count_query_members(_query_members), do: 0

  defp count_value(value) when is_map(value), do: map_size(value)
  defp count_value(value) when is_list(value), do: length(value)
  defp count_value(nil), do: 0
  defp count_value(_value), do: 1

  defp runtime_placeholders(domain) do
    placeholders =
      domain
      |> collect_placeholders(["domain"], [])
      |> Enum.sort_by(&Map.get(&1, "path"))

    by_type = placeholders |> Enum.map(& &1["type"]) |> frequencies()

    %{
      "count" => length(placeholders),
      "by_type" => by_type,
      "paths" => placeholders
    }
  end

  defp collect_placeholders(%{} = map, path, acc) do
    case map_get(map, "$selecto_export") do
      nil ->
        Enum.reduce(map, acc, fn {key, value}, path_acc ->
          collect_placeholders(value, path ++ [to_string(key)], path_acc)
        end)

      type ->
        [
          %{
            "path" => Enum.join(path, "."),
            "type" => to_string(type),
            "inspect" => map_get(map, "inspect")
          }
          | acc
        ]
    end
  end

  defp collect_placeholders(values, path, acc) when is_list(values) do
    values
    |> Enum.with_index()
    |> Enum.reduce(acc, fn {value, index}, path_acc ->
      collect_placeholders(value, path ++ [Integer.to_string(index)], path_acc)
    end)
  end

  defp collect_placeholders(_value, _path, acc), do: acc

  defp frequencies(values) do
    Enum.reduce(values, %{}, fn value, acc ->
      Map.update(acc, value, 1, &(&1 + 1))
    end)
  end

  defp section_placeholder_count(runtime_placeholders, section) do
    section_path = "domain.#{section}"

    runtime_placeholders
    |> map_get("paths", [])
    |> Enum.count(fn placeholder ->
      path = map_get(placeholder, "path", "")

      path == section_path or String.starts_with?(path, "#{section_path}.")
    end)
  end

  defp map_get(map, key, default \\ nil)

  defp map_get(map, key, default) when is_map(map) and is_binary(key) do
    atom_key = existing_atom(key)

    cond do
      Map.has_key?(map, key) -> Map.get(map, key)
      atom_key && Map.has_key?(map, atom_key) -> Map.get(map, atom_key)
      true -> default
    end
  end

  defp map_get(map, key, default) when is_map(map) and is_atom(key) do
    string_key = Atom.to_string(key)

    cond do
      Map.has_key?(map, key) -> Map.get(map, key)
      Map.has_key?(map, string_key) -> Map.get(map, string_key)
      true -> default
    end
  end

  defp map_get(_map, _key, default), do: default

  defp list_or_empty(value) when is_list(value), do: value
  defp list_or_empty(_value), do: []

  defp existing_atom(value) do
    String.to_existing_atom(value)
  rescue
    ArgumentError -> nil
  end
end
