defmodule SelectoMix.RawPersistence do
  @moduledoc false

  def parse_adapter(nil), do: {:ok, :ecto}
  def parse_adapter(""), do: {:ok, :ecto}
  def parse_adapter(adapter) when is_atom(adapter), do: parse_adapter(Atom.to_string(adapter))

  def parse_adapter(adapter) when is_binary(adapter) do
    case String.downcase(String.trim(adapter)) do
      "" -> {:ok, :ecto}
      "postgres" -> {:ok, :postgresql}
      "postgresql" -> {:ok, :postgresql}
      "sqlite" -> {:ok, :sqlite}
      other -> {:error, "unsupported raw persistence adapter #{inspect(other)}"}
    end
  end

  def raw_mode?(:ecto), do: false
  def raw_mode?(_mode), do: true

  def adapter_module(:postgresql), do: SelectoDBPostgreSQL.Adapter
  def adapter_module(:sqlite), do: SelectoDBSQLite.Adapter

  defp current_timestamp_sql(:postgresql), do: "NOW()"
  defp current_timestamp_sql(:sqlite), do: "CURRENT_TIMESTAMP"

  def connection_name(app_name, opts) do
    opts[:connection_name] || "#{app_name}.Database"
  end

  def saved_views_sql(config) do
    case config.adapter_mode do
      :postgresql ->
        """
        -- SavedViews table for SelectoComponents
        -- Generated by mix selecto.gen.saved_views --adapter postgresql

        CREATE TABLE IF NOT EXISTS #{config.table_name} (
          id BIGSERIAL PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          context VARCHAR(255) NOT NULL,
          params JSONB NOT NULL DEFAULT '{}',
          inserted_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        );

        CREATE UNIQUE INDEX IF NOT EXISTS idx_#{config.table_name}_name_context
          ON #{config.table_name} (name, context);
        """

      :sqlite ->
        """
        -- SavedViews table for SelectoComponents
        -- Generated by mix selecto.gen.saved_views --adapter sqlite

        CREATE TABLE IF NOT EXISTS #{config.table_name} (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL,
          context TEXT NOT NULL,
          params TEXT NOT NULL DEFAULT '{}',
          inserted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE UNIQUE INDEX IF NOT EXISTS idx_#{config.table_name}_name_context
          ON #{config.table_name} (name, context);
        """
    end
  end

  def saved_views_context(config) do
    p1 = placeholder(config.adapter_mode, 1)
    p2 = placeholder(config.adapter_mode, 2)
    p3 = placeholder(config.adapter_mode, 3)
    adapter_module = inspect(adapter_module(config.adapter_mode))

    """
    defmodule #{config.context_module} do
      @moduledoc \"\"\"
      Context module implementing SelectoComponents.SavedViews behaviour.

      Uses #{config.adapter_mode} persistence via #{adapter_module}.

      Generated by mix selecto.gen.saved_views --adapter #{config.adapter_mode}
      \"\"\"

      defmacro __using__(_opts \\ []) do
        conn_name = #{inspect(config.connection_name)}
        table = #{inspect(config.table_name)}
        adapter_module = #{adapter_module}
        adapter_name = #{inspect(config.adapter_mode)}

        quote bind_quoted: [
                conn_name: conn_name,
                table: table,
                adapter_module: adapter_module,
                adapter_name: adapter_name
              ] do
          @behaviour SelectoComponents.SavedViews

          @saved_views_conn conn_name
          @saved_views_table table
          @saved_views_adapter adapter_module
          @saved_views_adapter_name adapter_name

          def get_view(name, context) do
            context = scoped_context(context)

            query =
              "SELECT id, name, context, params, inserted_at, updated_at FROM \#{@saved_views_table} WHERE context = #{p1} AND name = #{p2}"

            case execute(query, [context, name]) do
              {:ok, %{rows: [row], columns: cols}} -> row_to_map(cols, row)
              {:ok, %{rows: []}} -> nil
              {:error, _} -> nil
            end
          end

          def save_view(name, context, params) do
            context = scoped_context(context)
            encoded_params = Jason.encode!(params)

            case get_view(name, context) do
              nil ->
                query =
                  "INSERT INTO \#{@saved_views_table} (name, context, params, inserted_at, updated_at) VALUES (#{p1}, #{p2}, #{p3}, #{current_timestamp_sql(config.adapter_mode)}, #{current_timestamp_sql(config.adapter_mode)})"

                case execute(query, [name, context, encoded_params]) do
                  {:ok, _} -> get_view(name, context)
                  {:error, error} -> {:error, error}
                end

              _existing ->
                query =
                  "UPDATE \#{@saved_views_table} SET params = #{p3}, updated_at = #{current_timestamp_sql(config.adapter_mode)} WHERE name = #{p1} AND context = #{p2}"

                case execute(query, [name, context, encoded_params]) do
                  {:ok, _} -> get_view(name, context)
                  {:error, error} -> {:error, error}
                end
            end
          end

          def get_view_names(context) do
            context = scoped_context(context)
            query = "SELECT name FROM \#{@saved_views_table} WHERE context = #{p1} ORDER BY name"

            case execute(query, [context]) do
              {:ok, %{rows: rows}} -> Enum.map(rows, fn [name] -> name end)
              {:error, _} -> []
            end
          end

          def list_views(context) do
            context = scoped_context(context)

            query =
              "SELECT id, name, context, params, inserted_at, updated_at FROM \#{@saved_views_table} WHERE context = #{p1} ORDER BY updated_at DESC, name ASC"

            case execute(query, [context]) do
              {:ok, %{rows: rows, columns: cols}} -> Enum.map(rows, &row_to_map(cols, &1))
              {:error, _} -> []
            end
          end

          def delete_view(name, context) do
            context = scoped_context(context)

            case get_view(name, context) do
              nil -> {:error, :not_found}
              view ->
                query = "DELETE FROM \#{@saved_views_table} WHERE name = #{p1} AND context = #{p2}"

                case execute(query, [name, context]) do
                  {:ok, _} -> {:ok, view}
                  {:error, error} -> {:error, error}
                end
            end
          end

          def rename_view(old_name, new_name, context) do
            context = scoped_context(context)
            trimmed_name = String.trim(new_name || "")

            cond do
              trimmed_name == "" -> {:error, :invalid_name}
              old_name == trimmed_name ->
                case get_view(old_name, context) do
                  nil -> {:error, :not_found}
                  view -> {:ok, view}
                end

              get_view(trimmed_name, context) ->
                {:error, :already_exists}

              true ->
                query = "UPDATE \#{@saved_views_table} SET name = #{p2}, updated_at = #{current_timestamp_sql(config.adapter_mode)} WHERE name = #{p1} AND context = #{p3}"

                case execute(query, [old_name, trimmed_name, context]) do
                  {:ok, _} ->
                    case get_view(trimmed_name, context) do
                      nil -> {:error, :not_found}
                      view -> {:ok, view}
                    end

                  {:error, error} -> {:error, error}
                end
            end
          end

          def decode_view(view) when is_map(view) do
            view["params"] || view[:params]
          end

          defp execute(query, params) do
            @saved_views_adapter.execute(@saved_views_conn, query, params, [])
          end

          defp row_to_map(columns, row) do
            columns
            |> Enum.zip(row)
            |> Enum.into(%{}, fn {column, value} ->
              {column, normalize_column_value(column, value)}
            end)
          end

          defp normalize_column_value("params", value), do: decode_json(value)
          defp normalize_column_value(_column, value), do: value

          defp decode_json(value) when is_map(value), do: value

          defp decode_json(value) when is_binary(value) do
            case Jason.decode(value) do
              {:ok, decoded} -> decoded
              _ -> %{}
            end
          end

          defp decode_json(_value), do: %{}

          defp scoped_context(context) do
            case context do
              %{} = context_map ->
                raw_context =
                  Map.get(context_map, :context) ||
                    Map.get(context_map, "context") ||
                    Map.get(context_map, :path) ||
                    Map.get(context_map, "path") ||
                    "default"

                tenant_context =
                  Map.get(context_map, :tenant) ||
                    Map.get(context_map, "tenant") ||
                    %{tenant_id: Map.get(context_map, :tenant_id) || Map.get(context_map, "tenant_id")}

                if Code.ensure_loaded?(SelectoComponents.Tenant) do
                  SelectoComponents.Tenant.scoped_context(raw_context, tenant_context)
                else
                  raw_context
                end

              _ ->
                context
            end
          end

          defp current_timestamp_sql(:postgresql), do: "NOW()"
          defp current_timestamp_sql(:sqlite), do: "CURRENT_TIMESTAMP"
        end
      end
    end
    """
  end

  def saved_view_configs_sql(config) do
    case config.adapter_mode do
      :postgresql ->
        """
        -- SavedViewConfigs table for SelectoComponents
        -- Generated by mix selecto.gen.saved_view_configs --adapter postgresql

        CREATE TABLE IF NOT EXISTS #{config.table_name} (
          id BIGSERIAL PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          context VARCHAR(255) NOT NULL,
          view_type VARCHAR(50) NOT NULL,
          params JSONB NOT NULL DEFAULT '{}',
          user_id VARCHAR(255),
          description TEXT,
          is_public BOOLEAN NOT NULL DEFAULT false,
          version INTEGER NOT NULL DEFAULT 1,
          inserted_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        );

        CREATE UNIQUE INDEX IF NOT EXISTS idx_#{config.table_name}_name_context_view_type_user
          ON #{config.table_name} (name, context, view_type, user_id);
        """

      :sqlite ->
        """
        -- SavedViewConfigs table for SelectoComponents
        -- Generated by mix selecto.gen.saved_view_configs --adapter sqlite

        CREATE TABLE IF NOT EXISTS #{config.table_name} (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL,
          context TEXT NOT NULL,
          view_type TEXT NOT NULL,
          params TEXT NOT NULL DEFAULT '{}',
          user_id TEXT,
          description TEXT,
          is_public INTEGER NOT NULL DEFAULT 0,
          version INTEGER NOT NULL DEFAULT 1,
          inserted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE UNIQUE INDEX IF NOT EXISTS idx_#{config.table_name}_name_context_view_type_user
          ON #{config.table_name} (name, context, view_type, user_id);
        """
    end
  end

  def saved_view_configs_context(config) do
    p1 = placeholder(config.adapter_mode, 1)
    p2 = placeholder(config.adapter_mode, 2)
    p3 = placeholder(config.adapter_mode, 3)
    p4 = placeholder(config.adapter_mode, 4)
    p5 = placeholder(config.adapter_mode, 5)
    p6 = placeholder(config.adapter_mode, 6)
    p7 = placeholder(config.adapter_mode, 7)
    adapter_module = inspect(adapter_module(config.adapter_mode))

    """
    defmodule #{config.context_module} do
      @moduledoc \"\"\"
      Adapter-backed context module for saved view configurations with view type separation.

      Generated by mix selecto.gen.saved_view_configs --adapter #{config.adapter_mode}
      \"\"\"

      defmacro __using__(_opts \\ []) do
        conn_name = #{inspect(config.connection_name)}
        table = #{inspect(config.table_name)}
        adapter_module = #{adapter_module}
        adapter_name = #{inspect(config.adapter_mode)}

        quote bind_quoted: [
                conn_name: conn_name,
                table: table,
                adapter_module: adapter_module,
                adapter_name: adapter_name
              ] do
          @view_config_conn conn_name
          @view_config_table table
          @view_config_adapter adapter_module
          @view_config_adapter_name adapter_name

          def get_view_config(name, context, view_type, opts \\ []) do
            user_id = Keyword.get(opts, :user_id)

            {query, params} =
              if user_id do
                {
                  "SELECT * FROM \#{@view_config_table} WHERE name = #{p1} AND context = #{p2} AND view_type = #{p3} AND (user_id = #{p4} OR is_public = #{truthy_sql_literal(config.adapter_mode)}) LIMIT 1",
                  [name, context, view_type, user_id]
                }
              else
                {
                  "SELECT * FROM \#{@view_config_table} WHERE name = #{p1} AND context = #{p2} AND view_type = #{p3} AND is_public = #{truthy_sql_literal(config.adapter_mode)} LIMIT 1",
                  [name, context, view_type]
                }
              end

            case execute(query, params) do
              {:ok, %{rows: [row], columns: cols}} -> row_to_map(cols, row)
              {:ok, %{rows: []}} -> nil
              {:error, _} -> nil
            end
          end

          def save_view_config(name, context, view_type, params, opts \\ []) do
            user_id = Keyword.get(opts, :user_id)
            description = Keyword.get(opts, :description)
            is_public = persist_boolean(Keyword.get(opts, :is_public, false))
            json_params = Jason.encode!(params)

            case get_view_config(name, context, view_type, user_id: user_id) do
              nil ->
                query =
                  "INSERT INTO \#{@view_config_table} (name, context, view_type, params, user_id, description, is_public, version, inserted_at, updated_at) VALUES (#{p1}, #{p2}, #{p3}, #{p4}, #{p5}, #{p6}, #{p7}, 1, #{current_timestamp_sql(config.adapter_mode)}, #{current_timestamp_sql(config.adapter_mode)})"

                case execute(query, [name, context, view_type, json_params, user_id, description, is_public]) do
                  {:ok, _} -> {:ok, get_view_config(name, context, view_type, user_id: user_id)}
                  {:error, error} -> {:error, error}
                end

              %{"user_id" => existing_user_id} = existing ->
                update_view_config(name, context, view_type, params,
                  user_id: existing_user_id || user_id,
                  description: description,
                  is_public: Keyword.get(opts, :is_public, false),
                  existing: existing
                )
            end
          end

          def list_view_configs(context, view_type, opts \\ []) do
            user_id = Keyword.get(opts, :user_id)
            include_public = Keyword.get(opts, :include_public, true)

            {query, params} =
              cond do
                user_id && include_public ->
                  {
                    "SELECT * FROM \#{@view_config_table} WHERE context = #{p1} AND view_type = #{p2} AND (user_id = #{p3} OR is_public = #{truthy_sql_literal(config.adapter_mode)}) ORDER BY updated_at DESC",
                    [context, view_type, user_id]
                  }

                user_id ->
                  {
                    "SELECT * FROM \#{@view_config_table} WHERE context = #{p1} AND view_type = #{p2} AND user_id = #{p3} ORDER BY updated_at DESC",
                    [context, view_type, user_id]
                  }

                include_public ->
                  {
                    "SELECT * FROM \#{@view_config_table} WHERE context = #{p1} AND view_type = #{p2} AND is_public = #{truthy_sql_literal(config.adapter_mode)} ORDER BY updated_at DESC",
                    [context, view_type]
                  }

                true ->
                  {"SELECT * FROM \#{@view_config_table} WHERE 1 = 0", []}
              end

            case execute(query, params) do
              {:ok, %{rows: rows, columns: cols}} -> Enum.map(rows, &row_to_map(cols, &1))
              {:error, _} -> []
            end
          end

          def delete_view_config(name, context, view_type, opts \\ []) do
            user_id = Keyword.get(opts, :user_id)

            case get_view_config(name, context, view_type, user_id: user_id) do
              nil -> {:error, :not_found}
              %{"user_id" => ^user_id} = config_map ->
                query = "DELETE FROM \#{@view_config_table} WHERE id = #{p1}"

                case execute(query, [config_map["id"]]) do
                  {:ok, _} -> {:ok, config_map}
                  {:error, error} -> {:error, error}
                end

              _ -> {:error, :unauthorized}
            end
          end

          def update_view_config(name, context, view_type, params, opts \\ []) do
            user_id = Keyword.get(opts, :user_id)
            description = Keyword.get(opts, :description)
            is_public = Keyword.get(opts, :is_public)
            existing = Keyword.get(opts, :existing)

            config_map = existing || get_view_config(name, context, view_type, user_id: user_id)

            case config_map do
              nil ->
                {:error, :not_found}

              %{"user_id" => ^user_id} = config_map ->
                json_params = Jason.encode!(params)

                query =
                  "UPDATE \#{@view_config_table} SET params = #{p2}, description = COALESCE(#{p3}, description), is_public = COALESCE(#{p4}, is_public), version = version + 1, updated_at = #{current_timestamp_sql(config.adapter_mode)} WHERE id = #{p1}"

                public_param = if is_nil(is_public), do: nil, else: persist_boolean(is_public)

                case execute(query, [config_map["id"], json_params, description, public_param]) do
                  {:ok, _} -> {:ok, get_view_config(name, context, view_type, user_id: user_id)}
                  {:error, error} -> {:error, error}
                end

              _ ->
                {:error, :unauthorized}
            end
          end

          def get_view_config_names(context, view_type, opts \\ []) do
            list_view_configs(context, view_type, opts)
            |> Enum.map(&(&1["name"] || &1[:name]))
          end

          def decode_view_config(view_config) when is_map(view_config) do
            view_config["params"] || view_config[:params]
          end

          defp execute(query, params) do
            @view_config_adapter.execute(@view_config_conn, query, params, [])
          end

          defp row_to_map(columns, row) do
            columns
            |> Enum.zip(row)
            |> Enum.into(%{}, fn {column, value} ->
              {column, normalize_column_value(column, value)}
            end)
          end

          defp normalize_column_value("params", value), do: decode_json(value)
          defp normalize_column_value("is_public", value), do: normalize_boolean(value)
          defp normalize_column_value(_column, value), do: value

          defp decode_json(value) when is_map(value), do: value

          defp decode_json(value) when is_binary(value) do
            case Jason.decode(value) do
              {:ok, decoded} -> decoded
              _ -> %{}
            end
          end

          defp decode_json(_value), do: %{}

          defp normalize_boolean(value) when value in [true, 1, "1"], do: true
          defp normalize_boolean(value) when value in [false, 0, "0"], do: false
          defp normalize_boolean(value), do: value

          defp persist_boolean(value) when @view_config_adapter_name == :sqlite do
            if value, do: 1, else: 0
          end

          defp persist_boolean(value), do: value

          defp current_timestamp_sql(:postgresql), do: "NOW()"
          defp current_timestamp_sql(:sqlite), do: "CURRENT_TIMESTAMP"
        end
      end
    end
    """
  end

  def filter_sets_sql(config) do
    case config.adapter_mode do
      :postgresql ->
        """
        -- Filter sets table for SelectoComponents
        -- Generated by mix selecto.gen.filter_sets --adapter postgresql

        CREATE TABLE IF NOT EXISTS #{config.table} (
          id TEXT PRIMARY KEY,
          name VARCHAR(100) NOT NULL,
          description TEXT,
          domain VARCHAR(255) NOT NULL,
          filters JSONB NOT NULL DEFAULT '{}',
          user_id VARCHAR(255) NOT NULL,
          is_default BOOLEAN NOT NULL DEFAULT false,
          is_shared BOOLEAN NOT NULL DEFAULT false,
          is_system BOOLEAN NOT NULL DEFAULT false,
          usage_count INTEGER NOT NULL DEFAULT 0,
          inserted_at TIMESTAMP NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMP NOT NULL DEFAULT NOW()
        );

        CREATE INDEX IF NOT EXISTS idx_#{config.table}_user_domain ON #{config.table} (user_id, domain);
        CREATE UNIQUE INDEX IF NOT EXISTS idx_#{config.table}_user_domain_name ON #{config.table} (user_id, domain, name);
        """

      :sqlite ->
        """
        -- Filter sets table for SelectoComponents
        -- Generated by mix selecto.gen.filter_sets --adapter sqlite

        CREATE TABLE IF NOT EXISTS #{config.table} (
          id TEXT PRIMARY KEY,
          name TEXT NOT NULL,
          description TEXT,
          domain TEXT NOT NULL,
          filters TEXT NOT NULL DEFAULT '{}',
          user_id TEXT NOT NULL,
          is_default INTEGER NOT NULL DEFAULT 0,
          is_shared INTEGER NOT NULL DEFAULT 0,
          is_system INTEGER NOT NULL DEFAULT 0,
          usage_count INTEGER NOT NULL DEFAULT 0,
          inserted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_#{config.table}_user_domain ON #{config.table} (user_id, domain);
        CREATE UNIQUE INDEX IF NOT EXISTS idx_#{config.table}_user_domain_name ON #{config.table} (user_id, domain, name);
        """
    end
  end

  def filter_sets_context(config) do
    p1 = placeholder(config.adapter_mode, 1)
    p2 = placeholder(config.adapter_mode, 2)
    p3 = placeholder(config.adapter_mode, 3)
    p4 = placeholder(config.adapter_mode, 4)
    p5 = placeholder(config.adapter_mode, 5)
    p6 = placeholder(config.adapter_mode, 6)
    p7 = placeholder(config.adapter_mode, 7)
    p8 = placeholder(config.adapter_mode, 8)
    adapter_module = inspect(adapter_module(config.adapter_mode))

    """
    defmodule #{config.context_module} do
      @moduledoc \"\"\"
      Context for managing saved filter sets.
      Implements SelectoComponents.FilterSetsBehaviour using #{config.adapter_mode} persistence.
      \"\"\"

      @behaviour SelectoComponents.FilterSetsBehaviour

      @conn #{inspect(config.connection_name)}
      @table #{inspect(config.table)}
      @adapter #{adapter_module}
      @adapter_name #{inspect(config.adapter_mode)}

      @impl true
      def list_personal_filter_sets(user_id, domain) do
        query =
          "SELECT * FROM \#{@table} WHERE user_id = #{p1} AND domain = #{p2} AND is_system = #{false_sql_literal(config.adapter_mode)} ORDER BY is_default DESC, name ASC"

        query_rows(query, [user_id, scoped_domain(domain)])
      end

      @impl true
      def list_shared_filter_sets(_user_id, domain) do
        query =
          "SELECT * FROM \#{@table} WHERE is_shared = #{truthy_sql_literal(config.adapter_mode)} AND domain = #{p1} AND is_system = #{false_sql_literal(config.adapter_mode)} ORDER BY name ASC"

        query_rows(query, [scoped_domain(domain)])
      end

      @impl true
      def list_system_filter_sets(domain) do
        query =
          "SELECT * FROM \#{@table} WHERE is_system = #{truthy_sql_literal(config.adapter_mode)} AND domain = #{p1} ORDER BY name ASC"

        query_rows(query, [scoped_domain(domain)])
      end

      @impl true
      def get_filter_set(id, user_id) do
        query = "SELECT * FROM \#{@table} WHERE id = #{p1}"

        case query_rows(query, [id]) do
          [] -> {:error, :not_found}
          [%{"is_system" => true} = fs] -> {:ok, fs}
          [%{"is_shared" => true} = fs] -> {:ok, fs}
          [%{"user_id" => ^user_id} = fs] -> {:ok, fs}
          _ -> {:error, :unauthorized}
        end
      end

      @impl true
      def create_filter_set(attrs) do
        attrs = atomize_keys(attrs)
        attrs = Map.put_new(attrs, :id, generate_id())
        attrs = Map.update(attrs, :domain, nil, &scoped_domain/1)
        maybe_unset_defaults(attrs)

        query =
          "INSERT INTO \#{@table} (id, name, description, domain, filters, user_id, is_default, is_shared, is_system, usage_count, inserted_at, updated_at) VALUES (#{p1}, #{p2}, #{p3}, #{p4}, #{p5}, #{p6}, #{p7}, #{p8}, ?, 0, #{current_timestamp_sql(config.adapter_mode)}, #{current_timestamp_sql(config.adapter_mode)})"

        params = [
          attrs[:id],
          attrs[:name],
          attrs[:description],
          attrs[:domain],
          Jason.encode!(attrs[:filters] || %{}),
          attrs[:user_id],
          persist_boolean(attrs[:is_default] || false),
          persist_boolean(attrs[:is_shared] || false),
          persist_boolean(attrs[:is_system] || false)
        ]

        case execute(query, params) do
          {:ok, _} -> get_filter_set(attrs[:id], attrs[:user_id])
          {:error, error} -> {:error, error}
        end
      end

      @impl true
      def update_filter_set(id, attrs, user_id) do
        attrs = atomize_keys(attrs)

        with {:ok, fs} <- get_filter_set(id, user_id),
             false <- fs["is_system"] do
          merged = Map.merge(fs, stringify_keys(attrs))
          maybe_unset_defaults(atomize_keys(merged))

          query =
            "UPDATE \#{@table} SET name = COALESCE(#{p2}, name), description = COALESCE(#{p3}, description), filters = COALESCE(#{p4}, filters), is_default = COALESCE(#{p5}, is_default), is_shared = COALESCE(#{p6}, is_shared), updated_at = #{current_timestamp_sql(config.adapter_mode)} WHERE id = #{p1}"

          params = [
            id,
            attrs[:name],
            attrs[:description],
            if(attrs[:filters], do: Jason.encode!(attrs[:filters]), else: nil),
            persist_boolean_or_nil(attrs[:is_default]),
            persist_boolean_or_nil(attrs[:is_shared])
          ]

          case execute(query, params) do
            {:ok, _} -> get_filter_set(id, user_id)
            {:error, error} -> {:error, error}
          end
        else
          true -> {:error, :cannot_modify_system}
          error -> error
        end
      end

      @impl true
      def delete_filter_set(id, user_id) do
        with {:ok, fs} <- get_filter_set(id, user_id),
             false <- fs["is_system"],
             true <- fs["user_id"] == user_id do
          case execute("DELETE FROM \#{@table} WHERE id = #{p1}", [id]) do
            {:ok, _} -> {:ok, fs}
            {:error, error} -> {:error, error}
          end
        else
          true -> {:error, :cannot_delete_system}
          false -> {:error, :unauthorized}
          error -> error
        end
      end

      @impl true
      def set_default_filter_set(id, user_id) do
        with {:ok, fs} <- get_filter_set(id, user_id) do
          _ = execute(
            "UPDATE \#{@table} SET is_default = #{false_sql_literal(config.adapter_mode)} WHERE user_id = #{p1} AND domain = #{p2} AND is_default = #{truthy_sql_literal(config.adapter_mode)}",
            [user_id, fs["domain"]]
          )

          case execute(
                 "UPDATE \#{@table} SET is_default = #{truthy_sql_literal(config.adapter_mode)}, updated_at = #{current_timestamp_sql(config.adapter_mode)} WHERE id = #{p1}",
                 [id]
               ) do
            {:ok, _} -> get_filter_set(id, user_id)
            {:error, error} -> {:error, error}
          end
        end
      end

      @impl true
      def get_default_filter_set(user_id, domain) do
        query =
          "SELECT * FROM \#{@table} WHERE user_id = #{p1} AND domain = #{p2} AND is_default = #{truthy_sql_literal(config.adapter_mode)}"

        case query_rows(query, [user_id, scoped_domain(domain)]) do
          [fs] -> fs
          _ -> nil
        end
      end

      @impl true
      def increment_usage_count(id) do
        _ = execute("UPDATE \#{@table} SET usage_count = usage_count + 1 WHERE id = #{p1}", [id])
        :ok
      end

      @impl true
      def duplicate_filter_set(id, new_name, user_id) do
        with {:ok, source} <- get_filter_set(id, user_id) do
          create_filter_set(%{
            name: new_name,
            description: source["description"],
            domain: source["domain"],
            filters: source["filters"],
            user_id: user_id,
            is_default: false,
            is_shared: false,
            is_system: false
          })
        end
      end

      defp execute(query, params) do
        @adapter.execute(@conn, query, params, [])
      end

      defp query_rows(query, params) do
        case execute(query, params) do
          {:ok, %{rows: rows, columns: cols}} -> Enum.map(rows, &row_to_map(cols, &1))
          {:error, _} -> []
        end
      end

      defp row_to_map(columns, row) do
        columns
        |> Enum.zip(row)
        |> Enum.into(%{}, fn {column, value} -> {column, normalize_column_value(column, value)} end)
      end

      defp normalize_column_value("filters", value) when is_binary(value) do
        case Jason.decode(value) do
          {:ok, decoded} -> decoded
          _ -> %{}
        end
      end

      defp normalize_column_value("filters", value) when is_map(value), do: value
      defp normalize_column_value(column, value) when column in ["is_default", "is_shared", "is_system"] do
        value in [true, 1, "1"]
      end
      defp normalize_column_value(_column, value), do: value

      defp atomize_keys(map) when is_map(map) do
        allowed_keys = %{
          "id" => :id,
          "name" => :name,
          "description" => :description,
          "domain" => :domain,
          "filters" => :filters,
          "user_id" => :user_id,
          "is_default" => :is_default,
          "is_shared" => :is_shared,
          "is_system" => :is_system,
          "usage_count" => :usage_count,
          "inserted_at" => :inserted_at,
          "updated_at" => :updated_at
        }

        map
        |> Enum.map(fn
          {k, v} when is_binary(k) ->
            case Map.get(allowed_keys, k) do
              nil -> nil
              allowed_key -> {allowed_key, v}
            end

          {k, v} -> {k, v}
        end)
        |> Enum.reject(&is_nil/1)
        |> Map.new()
      end

      defp stringify_keys(map) when is_map(map) do
        Enum.into(map, %{}, fn {k, v} -> {to_string(k), v} end)
      end

      defp maybe_unset_defaults(attrs) do
        if attrs[:is_default] do
          user_id = attrs[:user_id]
          domain = attrs[:domain]

          if user_id && domain do
            _ = execute(
              "UPDATE \#{@table} SET is_default = #{false_sql_literal(config.adapter_mode)} WHERE user_id = #{p1} AND domain = #{p2} AND is_default = #{truthy_sql_literal(config.adapter_mode)}",
              [user_id, domain]
            )
          end
        end
      end

      defp generate_id do
        Base.url_encode64(:crypto.strong_rand_bytes(12), padding: false)
      end

      defp persist_boolean(value) when @adapter_name == :sqlite, do: if(value, do: 1, else: 0)
      defp persist_boolean(value), do: value
      defp persist_boolean_or_nil(nil), do: nil
      defp persist_boolean_or_nil(value), do: persist_boolean(value)

      defp current_timestamp_sql(:postgresql), do: "NOW()"
      defp current_timestamp_sql(:sqlite), do: "CURRENT_TIMESTAMP"

      defp scoped_domain(domain) do
        case domain do
          %{} = domain_map ->
            raw_domain =
              Map.get(domain_map, :domain) ||
                Map.get(domain_map, "domain") ||
                Map.get(domain_map, :path) ||
                Map.get(domain_map, "path") ||
                "default"

            tenant_context =
              Map.get(domain_map, :tenant) ||
                Map.get(domain_map, "tenant") ||
                %{tenant_id: Map.get(domain_map, :tenant_id) || Map.get(domain_map, "tenant_id")}

            if Code.ensure_loaded?(SelectoComponents.Tenant) do
              SelectoComponents.Tenant.scoped_context(raw_domain, tenant_context)
            else
              raw_domain
            end

          _ ->
            domain
        end
      end
    end
    """
  end

  def compatibility_notice(adapter_mode) do
    case adapter_mode do
      :postgresql ->
        "Run: mix selecto.setup --adapter postgresql or execute the generated SQL manually"

      :sqlite ->
        "Execute the generated SQL against your SQLite database before using the context"
    end
  end

  defp placeholder(:postgresql, index), do: "$#{index}"
  defp placeholder(:sqlite, _index), do: "?"

  defp truthy_sql_literal(:postgresql), do: "true"
  defp truthy_sql_literal(:sqlite), do: "1"
  defp false_sql_literal(:postgresql), do: "false"
  defp false_sql_literal(:sqlite), do: "0"
end
